services:
  database:
    image: postgres
    container_name: nlw-return
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nlw_return
    volumes:
      - pgdata:/data/postgres
    network_mode: 'host'
volumes:
  pgdata:
    driver: local
